[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "our-notes-update-monitor"
version = "0.1.0"
description = "Automated data and resource update tracker for BanG Dream! Our Notes."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "tzdata>=2024.1; platform_system == 'Windows'",
  "grpcio>=1.64,<2",
  "py3rijndael==0.3.3"
]

[project.scripts]
onwatch = "onwatch.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
